sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ntdash/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ntdash/react-test npm test

after_success:
  - docker build -t ntdash/m-client ./client
  - docker build -t ntdash/m-nginx ./nginx
  - docker build -t ntdash/m-server ./server
  - docker build -t ntdash/m-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ntdash/m-client
  - docker push ntdash/m-nginx
  - docker push ntdash/m-server
  - docker push ntdash/m-worker

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#   bucket_path: 'docker-multi'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
